import fs from "fs/promises"
import os from "os"
import { config as Config } from "../../config"
import { fileExists } from "../../util"
import { Redis } from "../Redis"
import { NodeFactory } from "../nodes/node-factory"
import { VPNFactory } from "../vpn/vpn-factory"

export class ConfigManager {
    static async initConfigDir() {
        if (!(await fileExists(Config.VPN.PATH)) && os.platform() === "linux") {
            await fs.mkdir(Config.VPN.PATH)
        }
    }

    static async publishServerConfig(node: "global" | string) {
        const _clients = await VPNFactory.getFromAllUsers()
        const clients = _clients.reduce(
            (arr, client) => {
                arr.push(
                    [
                        `# Client: ${client.alias} (${client.id})`,
                        "[Peer]",
                        `PublicKey = ${client.pub}`,
                        `PresharedKey = ${client.psk}`,
                        `AllowedIPs = ${client.ipv4}/32, ${client.ipv6}/128`,
                        "",
                    ].join("\n"),
                )

                return arr
            },
            [""],
        )

        const config = [
            "# Note: Do not edit this file directly. It is generated by the RadicalVPN server.",
            "# Your changes will be overwritten!",
            "",
            "# Server",
            "[Interface]",
            `PrivateKey = ${Config.VPN.SECRETS.PRIVATE_KEY}`,
            `Address = ${Config.VPN.WG_SERVER.IPS.V4}, ${Config.VPN.WG_SERVER.IPS.V6}`,
            "ListenPort = 51820",
            ...clients,
        ].join("\n")

        const redis = await Redis.getInstance()
        if (node === "all") {
            const nodes = await new NodeFactory().getAll()
            await Promise.all(
                nodes.map(async (_node) => {
                    const clientsRecieved = await redis.publish(
                        `publish_config:${_node.hostname}`,
                        config,
                    )
                    if (clientsRecieved === 0) {
                        console.log(`vpn node ${_node.hostname} is offline.`)
                    }
                }),
            )
        } else {
            const clientsRecieved = await redis.publish(
                `publish_config:${node}`,
                config,
            )
            if (clientsRecieved === 0) {
                console.log(`vpn node ${node} is offline.`)
            }
        }
    }
}
