name: Build and Push Docker Image

on:
    push:
        branches:
            - master

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.JS 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x

            - name: Install Dependencies
              run: npm ci

            - name: Code should be formatted
              run: npm run format

            - name: Code should be linted
              run: npm run lint

            - name: Build Docker Image
              run: |
                  docker build -t ghcr.io/radicalvpn/radicalvpn_backend:latest .
              shell: bash

            - name: Log in to GitHub Container Registry
              run: |
                  echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u radicalvpn --password-stdin
              shell: bash

            - name: Push Docker Image to GitHub Container Registry
              run: |
                  docker push ghcr.io/radicalvpn/radicalvpn_backend:latest
              shell: bash
